FROM oven/bun:1-alpine

WORKDIR /app

# Copy dependency manifests
COPY package.json  app.json tsconfig.json ./

# Install dependencies
RUN bun install

# Copy source tree
COPY . .

# Expose Metro Bundler & Expo Web ports
EXPOSE 8081 19000 19001 19002

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
ENV REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0

CMD ["bunx", "expo", "start", "--web", "--host", "lan"]
